# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

SRC_PATH = ENV['BITRISE_SOURCE_DIR']

APP_DOWNLOAD_URLS = ""

import ("../../mobile-scripts/fastlane/Fastfile")

default_platform(:android)

platform :android do
    desc "Make an Advanced Sample app QA build"
        lane :build_advanced_sample_qa do
            gradle(task: "clean :AdvancedSample:assembleDebug")
        end

    desc "Make a Basic Sample app QA build"
        lane :build_basic_sample_qa do
            gradle(task: "clean :BasicSample:assembleDebug")
        end

    desc "Make a Contact Survey app QA build"
        lane :build_contact_survey_qa do
            gradle(task: "clean :ContactSurvey:assembleDebug")
        end

    desc "Make a Custom InSession Invite app QA build"
        lane :build_custom_invite_qa do
            gradle(task: "clean :CustomInSessionInvite:assembleDebug")
        end

    desc "Make a Dba Sample app QA build"
        lane :build_dba_sample_qa do
            gradle(task: "clean :DbaSample:assembleDebug")
        end

    desc "Make a Digital Sample app QA build"
        lane :build_digital_sample_qa do
            gradle(task: "clean :DigitalSample:assembleDebug")
        end

    desc "Make a Kotlin Sample app QA build"
        lane :build_kotlin_sample_qa do
            gradle(task: "clean :KotlinSample:assembleDebug")
        end

    desc "Make a Localization Sample app QA build"
        lane :build_localization_sample_qa do
            gradle(task: "clean :LocalizationSample:assembleDebug")
        end
end
